# Sayak Mono Sans No Ligatures
# ----------------------------

[buildPlans.SayakMonoNL]
family = "Sayak Mono NL"
spacing = "normal"
serifs = "sans"
noCvSs = false 
exportGlyphNames = true 
noLigation = true

  [buildPlans.SayakMonoNL.variants]
  inherits = "ss08"

    [buildPlans.SayakMonoNL.variants.design]
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    j = "serifed"
    l = "zshaped"
    t = "bent-hook"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    eszet = "sulzbacher-descending-serifless"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    decorative-angle-brackets = "middle"

[buildPlans.SayakMonoNL.weights.light]
shape = 300
menu = 300 
css = 300 

[buildPlans.SayakMonoNL.weights.regular]
shape = 400
menu = 400 
css = 400 

[buildPlans.SayakMonoNL.weights.medium]
shape = 500
menu = 500 
css = 500 

[buildPlans.SayakMonoNL.weights.bold]
shape = 700
menu = 700 
css = 700 

[buildPlans.SayakMonoNL.slopes.upright]
angle = 0
shape = "upright"
menu = "upright" 
css = "normal" 

[buildPlans.SayakMonoNL.slopes.italic]
angle = 9.4 
shape = "italic"
menu = "italic" 
css = "italic" 

[buildPlans.SayakMonoNL.widths.normal]
shape = 600 
menu = 5
css = "normal"

 
# Sayak Mono Sans No Ligatures
# Narrower glyphs for terminals
# -----------------------------

[buildPlans.SayakMonoNLTerm]
family = "Sayak Mono NL Term"
spacing = "term"
serifs = "sans"
noCvSs = false 
exportGlyphNames = true 
noLigation = true

  [buildPlans.SayakMonoNLTerm.variants]
  inherits = "ss08"

    [buildPlans.SayakMonoNLTerm.variants.design]
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    j = "serifed"
    l = "zshaped"
    t = "bent-hook"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    eszet = "sulzbacher-descending-serifless"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    decorative-angle-brackets = "middle"

[buildPlans.SayakMonoNLTerm.weights.light]
shape = 300
menu = 300 
css = 300 

[buildPlans.SayakMonoNLTerm.weights.regular]
shape = 400
menu = 400 
css = 400 

[buildPlans.SayakMonoNLTerm.weights.medium]
shape = 500
menu = 500 
css = 500 

[buildPlans.SayakMonoNLTerm.weights.bold]
shape = 700
menu = 700 
css = 700 

[buildPlans.SayakMonoNLTerm.slopes.upright]
angle = 0
shape = "upright"
menu = "upright" 
css = "normal" 

[buildPlans.SayakMonoNLTerm.slopes.italic]
angle = 9.4 
shape = "italic"
menu = "italic" 
css = "italic" 

[buildPlans.SayakMonoNLTerm.widths.normal]
shape = 600 
menu = 5
css = "normal"


# Sayak Mono Sans with Ligatures
# ----------------------------

[buildPlans.SayakMono]
family = "Sayak Mono"
spacing = "normal"
serifs = "sans"
noCvSs = false 
exportGlyphNames = true 

  [buildPlans.SayakMono.variants]
  inherits = "ss08"

    [buildPlans.SayakMono.variants.design]
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    j = "serifed"
    l = "zshaped"
    t = "bent-hook"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    eszet = "sulzbacher-descending-serifless"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    decorative-angle-brackets = "middle"

  [buildPlans.SayakMono.ligations]
  inherits = "clike"

[buildPlans.SayakMono.weights.light]
shape = 300
menu = 300 
css = 300 

[buildPlans.SayakMono.weights.regular]
shape = 400
menu = 400 
css = 400 

[buildPlans.SayakMono.weights.medium]
shape = 500
menu = 500 
css = 500 

[buildPlans.SayakMono.weights.bold]
shape = 700
menu = 700 
css = 700 

[buildPlans.SayakMono.slopes.upright]
angle = 0
shape = "upright"
menu = "upright" 
css = "normal" 

[buildPlans.SayakMono.slopes.italic]
angle = 9.4 
shape = "italic"
menu = "italic" 
css = "italic" 

[buildPlans.SayakMono.widths.normal]
shape = 600
menu = 5
css = "normal"


# Sayak Mono Sans with Ligatures
# Narrower glyphs for terminals
# -----------------------------
 
[buildPlans.SayakMonoTerm]
family = "Sayak Mono Term"
spacing = "term"
serifs = "sans"
noCvSs = false 
exportGlyphNames = true 

  [buildPlans.SayakMonoTerm.variants]
  inherits = "ss08"

    [buildPlans.SayakMonoTerm.variants.design]
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    j = "serifed"
    l = "zshaped"
    t = "bent-hook"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    eszet = "sulzbacher-descending-serifless"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    decorative-angle-brackets = "middle"

  [buildPlans.SayakMonoTerm.ligations]
  inherits = "clike"

[buildPlans.SayakMonoTerm.weights.light]
shape = 300
menu = 300 
css = 300 

[buildPlans.SayakMonoTerm.weights.regular]
shape = 400
menu = 400 
css = 400 

[buildPlans.SayakMonoTerm.weights.medium]
shape = 500
menu = 500 
css = 500 

[buildPlans.SayakMonoTerm.weights.bold]
shape = 700
menu = 700 
css = 700 

[buildPlans.SayakMonoTerm.slopes.upright]
angle = 0
shape = "upright"
menu = "upright" 
css = "normal" 

[buildPlans.SayakMonoTerm.slopes.italic]
angle = 9.4 
shape = "italic"
menu = "italic" 
css = "italic" 

[buildPlans.SayakMonoTerm.widths.normal]
shape = 600
menu = 5
css = "normal"


# Sayak Sans
# To be used with the webfont generator
# ----------------------------

[buildPlans.SayakSans]
family = "Sayak Sans"
spacing = "quasi-proportional"
serifs = "sans"
noCvSs = false 
exportGlyphNames = true 

  [buildPlans.SayakSans.variants]
  inherits = "ss08"

    [buildPlans.SayakSans.variants.design]
    four = "closed-serifless"
    five = "oblique-arched-serifless"
    seven = "straight-serifed"
    eight = "two-circles"
    nine = "straight-bar"
    zero = "slashed"
    capital-a = "curly-serifless"
    capital-i = "serifed"
    capital-j = "serifed"
    capital-n = "standard-serifless"
    capital-v = "curly-serifless"
    capital-w = "curly-serifless"
    capital-x = "curly-serifless"
    capital-y = "curly-serifless"
    a = "double-storey-serifless"
    g = "single-storey-serifless"
    h = "straight-serifless"
    j = "serifed"
    l = "zshaped"
    t = "bent-hook"
    v = "curly-serifless"
    w = "curly-serifless"
    x = "curly-serifless"
    y = "straight-turn-serifless"
    eszet = "sulzbacher-descending-serifless"
    asterisk = "penta-low"
    underscore = "above-baseline"
    caret = "medium"
    paren = "normal"
    brace = "curly"
    number-sign = "slanted"
    ampersand = "closed"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "force-upright"
    question = "corner"
    decorative-angle-brackets = "middle"

  [buildPlans.SayakSans.ligations]
  inherits = "clike"

[buildPlans.SayakSans.weights.light]
shape = 300
menu = 300 
css = 300 

[buildPlans.SayakSans.weights.regular]
shape = 400
menu = 400 
css = 400 

[buildPlans.SayakSans.weights.medium]
shape = 500
menu = 500 
css = 500 

[buildPlans.SayakSans.weights.bold]
shape = 700
menu = 700 
css = 700 

[buildPlans.SayakSans.slopes.upright]
angle = 0
shape = "upright"
menu = "upright" 
css = "normal" 

[buildPlans.SayakSans.slopes.italic]
angle = 9.4 
shape = "italic"
menu = "italic" 
css = "italic" 

[buildPlans.SayakSans.widths.normal]
shape = 600
menu = 5
css = "normal"